[package]
name = "miva"
version = "0.1.3"
edition = "2021"
description = "The Miva programming language compiler"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
toml = "0.8"
sha2 = "0.10"
hex = "0.4"
miva-vm = { path = "../miva-vm" }
miva-frontend = { path = "../miva-frontend-rs" }
