use anyhow::{bail, Context, Result};
use std::fs;
use std::path::Path;

use super::color;

#[derive(clap::Args)]
pub struct Args {
    pub name: String,
    #[arg(short = 't')]
    pub type_: String,
}

fn main_miva_code() -> &'static str {
    "// main.miva
// Generated by Miva init
module main;
main = () => {
  println(\"Hello, World\");
}
"
}

fn lib_miva_code(modn: &str) -> String {
    format!(
        "// lib.miva
// Generated by Miva init
module {modn};
add = (ref a: int, ref b: int): int => {{
  return a + b;
}}
test add_test = (): int => {{
  assert!(add(1, 2) == 3);
  0;
}}
export add;
"
    )
}

fn toml_content(name: &str, type_: &str) -> String {
    format!(
        "[project]
name = \"{name}\"
version = \"0.1.0\"
type = \"{type_}\"

[env]

[scripts]
dev = \"miva run -b mvm\"
release = \"miva build -b llvm --release\"

[dependencies]
std = \"0.1.4\"
"
    )
}

pub fn exec(args: Args, _verbose: bool) -> Result<()> {
    let cwd = std::env::current_dir()?;

    if Path::new("miva.toml").exists() {
        bail!("project already initialized in this directory");
    }

    match args.type_.as_str() {
        "bin" | "lib" => {}
        _ => bail!("unknown project type {}", args.type_),
    }

    fs::write(cwd.join("miva.toml"), toml_content(&args.name, &args.type_))
        .context("failed to write miva.toml")?;

    fs::create_dir_all(cwd.join("src")).context("failed to create src directory")?;

    if args.type_ == "bin" {
        fs::write(cwd.join("src/main.miva"), main_miva_code())
            .context("failed to write src/main.miva")?;
    } else {
        fs::write(cwd.join("src/lib.miva"), lib_miva_code(&args.name))
            .context("failed to write src/lib.miva")?;
    }

    eprintln!(
        "{}",
        color::info(&format!(
            "initialized {} project '{}'",
            args.type_, args.name
        ))
    );
    Ok(())
}
